"""Task domain constants."""

TASK_STATUS_PENDING = "pending"
TASK_STATUS_COMPLETED = "completed"

TASK_PRIORITY_LOW = "low"
TASK_PRIORITY_NORMAL = "normal"
TASK_PRIORITY_HIGH = "high"

OPEN_TASK_STATUSES = (TASK_STATUS_PENDING,)
TASK_STATUSES = (TASK_STATUS_PENDING, TASK_STATUS_COMPLETED)
TASK_PRIORITIES = (TASK_PRIORITY_LOW, TASK_PRIORITY_NORMAL, TASK_PRIORITY_HIGH)
